### ISSUE TITLE
Can't access long path files and folders on windows

### ISSUE THREAD

**Issue by shmox** [gilbertchen/duplicacy-beta#11]
I am using windows 10 and tried to backup an angular.js application folder with many long path folders an files, the backup can't access these long path files and folders, even if i use -vss option, is it a bug or am i missing something ?

The backup ends with thes folders and files not backed up with warnings

**Comment by gilbertchen** [comment]
This has been fixed in release 0.1.10.

**Comment by shmox** [comment]
Thank you :+1:

**Comment by shmox** [comment]
Now i have this error:

Indexing C:\wamp\www\prototype
**Failed to list subdirectory: open** C:\wamp\www\prototype/ng-app/node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/registry-url/node_modules/npmconf/node_modules/once/node_modules/wrappy/test: **the file path is not found**

.....
