### ISSUE TITLE
Long path error on windows

### ISSUE THREAD

**Issue by shmox** [gilbertchen/duplicacy-beta#12]
Now i have this error in 0.1.10 release :

Indexing C:\wamp\www\prototype
**Failed to list subdirectory**: open C:\wamp\www\prototype/ng-app/node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/registry-url/node_modules/npmconf/node_modules/once/node_modules/wrappy/test: **the path is not found**

**Comment by gilbertchen** [comment]
That path happens to be 260 char long.  The maximum DOS-style path length is actually 259, not counting the terminating null char...

I updated the 0.1.10 build.  If you download it now you'll get the updated executable.

**Comment by shmox** [comment]
Okay it works thanks :+1:
