### ISSUE TITLE
Feature request:  pre- and post-backup scripts

### ISSUE THREAD

**Issue by jeff47** [gilbertchen/duplicacy-beta#14]
It might be helpful to users to be able to specify a shell script to run before and after backups.  (IE, to mount or unmount a remote filesystem prior to backup)  I can do this by putting the entire backup operation in a shell script, but then I lose the GUI.

**Comment by gilbertchen** [comment]
This has been implemented: https://github.com/gilbertchen/duplicacy-beta/blob/master/GUIDE.md#scripts
