### ISSUE TITLE
Can not copy from local disc to sftp.

### ISSUE THREAD

**Issue by usbpc102** [gilbertchen/duplicacy-beta#2]
I tried to create a second storage options with `duplicacy add -copy default server oma sftp://<some ip here>/backup`

After that I tired to copy the backup from the local disc to the sftp server with this command: 
`duplicity copy -to server`

and get this response:

`Copying snapshots to sftp://<some ip here>/backup was disabled by the preference`

Did I do something wrong or is this a bug?

**Comment by gilbertchen** [comment]
This is a bug.  There is a new release that fixed this bug.

**Comment by usbpc102** [comment]
Thank you!
