### ISSUE TITLE
Can it backup VMs? aka .raw and .qcow2 files while the respective machines are running?

### ISSUE THREAD

**Issue by ovizii** [gilbertchen/duplicacy-beta#8]
Of course if said machine was running something like say a MYSQL DB this wouldn't be an ideal solution but would you mind giving us some more insights into the feasibility of this?

**Comment by gilbertchen** [comment]
I use it myself to backup virtualbox files larger than 100G bytes, but I only do this when the virtual machines are shut down.

I think to get consistent backups when the virtual machines are running, you should at least create snapshots of the virtual disks and then backup the snapshots.

**Comment by ovizii** [comment]
hm, thanks for clarifying but I have a small and simple server with a 2 HD raid1 config and I don't have filestorage supporting snapshots. 

Anyway, how is duplicacy working out for you in terms of deduplication with these VMs? 
I'm thinking of backing up 4 LXCs which run the same OS to the same backup storage, should I expect huge space savings by deduplication kicking in?

**Comment by gilbertchen** [comment]
I didn't keep track of the duplication ratio, and these are all different versions of Windows ranging from XP to 10.

**Comment by ovizii** [comment]
Thanks.
